### ISSUE TITLE
Demo misses functions and can you give a complete one?

### ISSUE THREAD

**Issue by ypflll** [nivha/surface_networks_covers#2]
Missing definition of two functions in aggregate_predictions.m:
get_prediction_for_img
evaluate_mesh

Can you provide ? Thx.

**Comment by chosenjuan7** [comment]
Hi @ypflll have you found these functions in repository/ gptoolbox?

**Comment by nivha** [comment]
Hi @chosenjuan7 @ypflll 
Unfortunately I could not find these files.

**Comment by nivha** [comment]
Dear @chosenjuan7 @ypflll 

I managed to find the two missing files. 
Please check if you see them under matlab/api.

Best,
Niv
